### ISSUE TITLE
0.5.0: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [python-visualization/branca#112]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/docs/source/conf.py", line 26, in <module>
    from branca._version import get_versions
ModuleNotFoundError: No module named 'branca'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/docs/source/conf.py", line 26, in <module>
    from branca._version import get_versions
ModuleNotFoundError: No module named 'branca'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/docs/source/conf.py", line 26, in <module>
    from branca._version import get_versions
ModuleNotFoundError: No module named 'branca'
```
</details>

This can be fixed by patch like below:
```patch
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -12,9 +12,9 @@
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
 #
-# import os
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import os
+import sys
+sys.path.insert(0, os.path.abspath("../.."))


 # -- Project information -----------------------------------------------------
```

This patch fixes what is in the comment and that can of fix is suggested in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-
configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.0.2
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-branca.3 { element colormap } /home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.CssLink:: WARNING: py:class reference target not found: default False
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Div:: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Div:: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Div:: WARNING: py:class reference target not found: default '0%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Div:: WARNING: py:class reference target not found: default '0%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Div:: WARNING: py:class reference target not found: default 'relative'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Element:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Element:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Element.save:: WARNING: py:class reference target not found: file object
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Element.save:: WARNING: py:class reference target not found: default True
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: default "100%"
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: default "60%"
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: tuple of two int
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure.add_subplot:: WARNING: py:class reference target not found: >>>
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure.add_subplot:: WARNING: py:class reference target not found: # Create a div in the 5th cell of a 3rows x
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure.add_subplot:: WARNING: py:class reference target not found: grid
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Figure.add_subplot:: WARNING: py:class reference target not found: bottom-left
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Html:: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.Html:: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: default "100%"
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: default "60%"
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: tuple of two int
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.IFrame:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/element.py:docstring of branca.element.JavascriptLink:: WARNING: py:class reference target not found: default False
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.ColorMap:: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: list-like object with at least two colors.
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: default 0.
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: default 1.
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default 'linear'
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: list-like object
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: default 0.
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: default 1.
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap:: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:: WARNING: py:class reference target not found: list of floats
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.5.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:: WARNING: py:class reference target not found: default 10
done
build succeeded, 57 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2

**Comment by Conengmo** [comment]
@ocefpaf could you comment on this one?

**Comment by ocefpaf** [comment]
I'd rather have the module installed when running sphinx. I'm planning on working on the docs as soon as I finish #120

**Comment by ocefpaf** [comment]
Docs are building fine. @kloczek to solve that you can do a local edit install like `pip install -e .` and build the docs.

**Comment by kloczek** [comment]
> Docs are building fine. @kloczek to solve that you can do a local edit install like `pip install -e .` and build the docs.

Reported issu has nothing to do in what kind os tate is source tree.
Please try to use `-n` option during builnd docuemtation.

**Comment by kloczek** [comment]
Upatet `sphinx-build outpu (nor it is more warnings)
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-branca.3 { element colormap } /home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.CssLink:1: WARNING: py:class reference target not found: default False
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Div:1: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Div:1: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Div:1: WARNING: py:class reference target not found: default '0%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Div:1: WARNING: py:class reference target not found: default '0%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Div:1: WARNING: py:class reference target not found: default 'relative'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Element:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Element:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Element.save:1: WARNING: py:class reference target not found: file object
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Element.save:1: WARNING: py:class reference target not found: default True
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: default "100%"
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: default "60%"
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: two int
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure.add_subplot:1: WARNING: py:class reference target not found: >>>
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure.add_subplot:1: WARNING: py:class reference target not found: # Create a div in the 5th cell
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure.add_subplot:1: WARNING: py:class reference target not found: a 3rows x
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure.add_subplot:1: WARNING: py:class reference target not found: grid
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Figure.add_subplot:1: WARNING: py:class reference target not found: bottom-left
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Html:1: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.Html:1: WARNING: py:class reference target not found: default '100%'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: default "100%"
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: default "60%"
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: two int
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.IFrame:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/element.py:docstring of branca.element.JavascriptLink:1: WARNING: py:class reference target not found: default False
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.ColorMap:1: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: list-like object with at least two colors.
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: default 0.
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: default 1.
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default 'linear'
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.LinearColormap.to_step:1: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: list-like object
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: default 0.
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: default 1.
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: default 10
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:1: WARNING: py:class reference target not found: floats
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:1: WARNING: py:class reference target not found: default None
/home/tkloczko/rpmbuild/BUILD/branca-0.6.0/branca/colormap.py:docstring of branca.colormap.StepColormap.to_linear:1: WARNING: py:class reference target not found: default 10
done
build succeeded, 61 warnings.
```
</details>
